### ISSUE TITLE
Issue: Step 4.2 - 4.3

### ISSUE THREAD

**Issue by mkelleh2** [ronniegeraghty/Egit-Installation#16]
When I click next, I see a pop-up window asking for Login information even though I did not specify any credentials in 4.2 or in any steps previously. 

I used the following URI: https://github.com/mackennakelleher/ProjectExample.git

And I received this error:
https://github.com/mackennakelleher/ProjectExample.git: https://github.com/mackennakelleher/ProjectExample.git/info/refs?service=git-upload-pack not found: Not Found:

**Comment by thuymibm** [comment]
I have the same issue. Perhaps is there a step missing on either linking our repos to our github account or creating a project/repo online?
